RSS_FEEDS = [
    # ===== INDIAN NATIONAL NEWS (47 sources) =====
    {"name": "Times of India - Top Stories", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - India", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - World", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - Business", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - Tech", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - Sports", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Times of India - Entertainment", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "NDTV - Top Stories", "url": "http://feeds.feedburner.com/ndtvnews-top-stories", "country": "IN", "lang": "en"},
    {"name": "NDTV - India", "url": "http://feeds.feedburner.com/ndtvnews-top-stories", "country": "IN", "lang": "en"},
    {"name": "NDTV - World", "url": "https://feeds.feedburner.com/ndtvnews-world-news", "country": "IN", "lang": "en"},
    {"name": "NDTV - Business", "url": "http://feeds.feedburner.com/ndtvnews-top-stories", "country": "IN", "lang": "en"},
    {"name": "NDTV - Tech", "url": "http://feeds.feedburner.com/ndtvnews-top-stories", "country": "IN", "lang": "en"},
    {"name": "The Hindu - Home", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - National", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - International", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - Business", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - Sport", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - Science", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "The Hindu - Technology", "url": "https://www.thehindu.com/feeder/default.rss", "country": "IN", "lang": "en"},
    {"name": "Hindustan Times - Latest", "url": "https://www.hindustantimes.com/feeds/rss/latest/rssfeed.xml", "country": "IN", "lang": "en"},
    {"name": "Hindustan Times - Business", "url": "https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml", "country": "IN", "lang": "en"},
    {"name": "Hindustan Times - Tech", "url": "https://www.hindustantimes.com/feeds/rss/technology/rssfeed.xml", "country": "IN", "lang": "en"},
    {"name": "Hindustan Times - Sports", "url": "https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml", "country": "IN", "lang": "en"},
    {"name": "Indian Express - India", "url": "https://indianexpress.com/section/india/feed/", "country": "IN", "lang": "en"},
    {"name": "Indian Express - World", "url": "https://indianexpress.com/section/world/feed/", "country": "IN", "lang": "en"},
    {"name": "Indian Express - Business", "url": "https://indianexpress.com/section/business/feed/", "country": "IN", "lang": "en"},
    {"name": "Indian Express - Tech", "url": "https://indianexpress.com/section/technology/feed/", "country": "IN", "lang": "en"},
    {"name": "Indian Express - Sports", "url": "https://indianexpress.com/section/sports/feed/", "country": "IN", "lang": "en"},
    {"name": "India Today - India", "url": "https://www.indiatoday.in/rss/1206578", "country": "IN", "lang": "en"},
    {"name": "India Today - World", "url": "https://www.indiatoday.in/rss/1206580", "country": "IN", "lang": "en"},
    {"name": "India Today - Business", "url": "https://www.indiatoday.in/rss/1206582", "country": "IN", "lang": "en"},
    {"name": "News18 - India", "url": "https://www.news18.com/rss/india.xml", "country": "IN", "lang": "en"},
    {"name": "News18 - World", "url": "https://www.news18.com/rss/world.xml", "country": "IN", "lang": "en"},
    {"name": "Deccan Herald - Home", "url": "https://www.deccanherald.com/feed", "country": "IN", "lang": "en"},
    {"name": "Business Standard - Top", "url": "https://www.business-standard.com/rss/101.rss", "country": "IN", "lang": "en"},
    {"name": "LiveMint - News", "url": "https://www.livemint.com/rss/news", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Companies", "url": "https://www.livemint.com/rss/companies", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Tech", "url": "https://www.livemint.com/rss/technology", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Markets", "url": "https://www.livemint.com/rss/markets", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Politics", "url": "https://www.livemint.com/rss/politics", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Money", "url": "https://www.livemint.com/rss/money", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Industry", "url": "https://www.livemint.com/rss/industry", "country": "IN", "lang": "en"},
    {"name": "LiveMint - Opinion", "url": "https://www.livemint.com/rss/opinion", "country": "IN", "lang": "en"},
    {"name": "Economic Times - Top", "url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "lang": "en"},
    {"name": "Bar and Bench - Legal", "url": "https://www.barandbench.com/feed", "country": "IN", "lang": "en"},

    # ===== INTERNATIONAL NEWS (67 sources) =====
    {"name": "BBC - Top Stories", "url": "http://feeds.bbci.co.uk/news/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - World", "url": "https://feeds.bbci.co.uk/news/world/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Business", "url": "http://feeds.bbci.co.uk/news/business/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Technology", "url": "http://feeds.bbci.co.uk/news/technology/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Politics", "url": "http://feeds.bbci.co.uk/news/politics/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Science", "url": "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Health", "url": "http://feeds.bbci.co.uk/news/health/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - UK", "url": "http://feeds.bbci.co.uk/news/uk/rss.xml", "country": "GB", "lang": "en"},
    {"name": "BBC - Entertainment", "url": "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml", "country": "GB", "lang": "en"},
    {"name": "CNN - Top Stories", "url": "http://rss.cnn.com/rss/edition.rss", "country": "US", "lang": "en"},
    {"name": "CNN - World", "url": "http://rss.cnn.com/rss/edition_world.rss", "country": "US", "lang": "en"},
    {"name": "CNN - US", "url": "http://rss.cnn.com/rss/cnn_us.rss", "country": "US", "lang": "en"},
    {"name": "CNN - Business", "url": "http://rss.cnn.com/rss/money_latest.rss", "country": "US", "lang": "en"},
    {"name": "CNN - Tech", "url": "http://rss.cnn.com/rss/cnn_tech.rss", "country": "US", "lang": "en"},
    {"name": "The Guardian - World", "url": "https://www.theguardian.com/world/rss", "country": "GB", "lang": "en"},
    {"name": "The Guardian - UK", "url": "https://www.theguardian.com/uk/rss", "country": "GB", "lang": "en"},
    {"name": "The Guardian - US", "url": "https://www.theguardian.com/us-news/rss", "country": "US", "lang": "en"},
    {"name": "The Guardian - Business", "url": "https://www.theguardian.com/business/rss", "country": "GB", "lang": "en"},
    {"name": "The Guardian - Technology", "url": "https://www.theguardian.com/technology/rss", "country": "GB", "lang": "en"},
    {"name": "The Guardian - Sport", "url": "https://www.theguardian.com/sport/rss", "country": "GB", "lang": "en"},
    {"name": "NY Times - Home", "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "country": "US", "lang": "en"},
    {"name": "NY Times - World", "url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", "country": "US", "lang": "en"},
    {"name": "NY Times - US", "url": "https://rss.nytimes.com/services/xml/rss/nyt/US.xml", "country": "US", "lang": "en"},
    {"name": "NY Times - Business", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "country": "US", "lang": "en"},
    {"name": "NY Times - Technology", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", "country": "US", "lang": "en"},
    {"name": "NY Times - Science", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", "country": "US", "lang": "en"},
    {"name": "Washington Post - World", "url": "https://feeds.washingtonpost.com/rss/world", "country": "US", "lang": "en"},
    {"name": "Washington Post - Politics", "url": "https://feeds.washingtonpost.com/rss/politics", "country": "US", "lang": "en"},
    {"name": "Washington Post - Business", "url": "https://feeds.washingtonpost.com/rss/business", "country": "US", "lang": "en"},
    {"name": "Wall Street Journal - World", "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml", "country": "US", "lang": "en"},
    {"name": "Wall Street Journal - Tech", "url": "https://feeds.a.dj.com/rss/RSSWSJD.xml", "country": "US", "lang": "en"},
    {"name": "Wall Street Journal - Markets", "url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml", "country": "US", "lang": "en"},
    {"name": "Al Jazeera - Top", "url": "https://www.aljazeera.com/xml/rss/all.xml", "country": "QA", "lang": "en"},
    {"name": "NPR - Top News", "url": "https://feeds.npr.org/1001/rss.xml", "country": "US", "lang": "en"},
    {"name": "NPR - World", "url": "https://feeds.npr.org/1004/rss.xml", "country": "US", "lang": "en"},
    {"name": "NPR - Business", "url": "https://feeds.npr.org/1014/rss.xml", "country": "US", "lang": "en"},
    {"name": "NPR - Technology", "url": "https://feeds.npr.org/1019/rss.xml", "country": "US", "lang": "en"},
    {"name": "Deutsche Welle - Top", "url": "https://rss.dw.com/xml/rss-en-all", "country": "DE", "lang": "en"},
    {"name": "France24 - Top", "url": "https://www.france24.com/en/rss", "country": "FR", "lang": "en"},
    {"name": "Euronews - Top", "url": "https://www.euronews.com/rss", "country": "FR", "lang": "en"},
    {"name": "Sky News - Top", "url": "http://feeds.skynews.com/feeds/rss/home.xml", "country": "GB", "lang": "en"},
    {"name": "CNBC - Top", "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html", "country": "US", "lang": "en"},
    {"name": "CNBC - World", "url": "https://www.cnbc.com/id/100727362/device/rss/rss.html", "country": "US", "lang": "en"},
    {"name": "NBC News - Top", "url": "https://feeds.nbcnews.com/nbcnews/public/news", "country": "US", "lang": "en"},
    {"name": "ABC News - Top", "url": "https://abcnews.go.com/abcnews/topstories", "country": "US", "lang": "en"},
    {"name": "CBS News - Top", "url": "https://www.cbsnews.com/latest/rss/main", "country": "US", "lang": "en"},
    {"name": "The Hill - Politics", "url": "https://thehill.com/news/feed", "country": "US", "lang": "en"},
    {"name": "Politico - Top", "url": "https://rss.politico.com/politics-news.xml", "country": "US", "lang": "en"},
    {"name": "Politico - Congress", "url": "https://rss.politico.com/congress.xml", "country": "US", "lang": "en"},
    {"name": "Politico - Healthcare", "url": "https://rss.politico.com/healthcare.xml", "country": "US", "lang": "en"},
    {"name": "Politico - Economy", "url": "https://rss.politico.com/economy.xml", "country": "US", "lang": "en"},
    {"name": "Politico - Defense", "url": "https://rss.politico.com/defense.xml", "country": "US", "lang": "en"},

    # ===== REPLACEMENTS FOR PERMANENTLY BROKEN SOURCES =====
    {"name": "Google News - Reuters", "url": "https://news.google.com/rss/search?q=site:reuters.com&hl=en-US&gl=US&ceid=US:en", "country": "GB", "lang": "en"},
    {"name": "Google News - Associated Press", "url": "https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en", "country": "US", "lang": "en"},
    {"name": "Bloomberg - Markets", "url": "https://feeds.bloomberg.com/markets/news.rss", "country": "US", "lang": "en"},
    {"name": "Forbes - Innovation", "url": "https://www.forbes.com/innovation/feed/", "country": "US", "lang": "en"},
    {"name": "Forbes - Business", "url": "https://www.forbes.com/business/feed/", "country": "US", "lang": "en"},
    {"name": "FT - World", "url": "https://www.ft.com/rss/world", "country": "GB", "lang": "en"},
    {"name": "The Independent - UK", "url": "https://www.independent.co.uk/rss", "country": "GB", "lang": "en"},
    {"name": "Time - Top", "url": "https://time.com/feed/", "country": "US", "lang": "en"},
    {"name": "Newsweek - Top", "url": "https://www.newsweek.com/rss", "country": "US", "lang": "en"},
    {"name": "The Atlantic", "url": "https://feeds.feedburner.com/TheAtlantic", "country": "US", "lang": "en"},
    {"name": "New Yorker - News", "url": "https://www.newyorker.com/feed/news", "country": "US", "lang": "en"},
    {"name": "The Telegraph - UK", "url": "https://www.telegraph.co.uk/rss", "country": "GB", "lang": "en"},
    {"name": "CBC - Top Stories", "url": "https://rss.cbc.ca/lineup/topstories.xml", "country": "CA", "lang": "en"},
    {"name": "ABC Australia - News", "url": "https://www.abc.net.au/news/feed/51120/rss.xml", "country": "AU", "lang": "en"},
]


RSS_FEEDS_BY_COUNTRY = {}
for feed in RSS_FEEDS:
    c = feed["country"]
    if c not in RSS_FEEDS_BY_COUNTRY:
        RSS_FEEDS_BY_COUNTRY[c] = []
    RSS_FEEDS_BY_COUNTRY[c].append(feed)
